services:
  webserver:
    build: .
    ports:
      - "10100:80"
    volumes:
      - ./frontend:/frontend:ro
      - ./nginx.conf:/app/nginx/nginx.conf:ro
    container_name: static-webserver
