version: '3.9'
services:
  webserver:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/frontend:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: static-webserver
